### PR TITLE
added manvi.html

### PR DESCRIPTION
**Pull request by Manvij30**

### CODE REVIEW

**Comment by unnown** [comment]
Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing'(hacktoberfest)
This will also ban the user for trying to abuse the system by doing marginal effort

**Comment by Manvij30** [comment]
> Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing'(hacktoberfest)
> This will also ban the user for trying to abuse the system by doing marginal effort

that was the event thing not spam or invalid.. dont comment the things you dont know

**Comment by Manvij30** [comment]
> Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing'(hacktoberfest)
> This will also ban the user for trying to abuse the system by doing marginal effort

that was the event thing not spam or invalid.. dont comment the things you dont know

**Comment by unnown** [comment]
Yes you are clearly not trying to spam right now...

**Comment by Manvij30** [comment]
thankyou

**Comment by loveneeshdhir** [comment]
There are syntax errors, please correct them and open the pr again

**Comment by loveneeshdhir** [comment]
> Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing'(hacktoberfest)
> This will also ban the user for trying to abuse the system by doing marginal effort

Hey, thanks for flagging this up actually I conducted a session for some beginners to get started with git and GitHub I think she may have confusion at that point of time.

**Pull request closed without merging**
